# Generated by Django 4.2.7 on 2023-12-18 20:32

from django.db import migrations, models
import explainable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=explainable.models.uploadtest, validators=[explainable.models.valCSV], verbose_name='Only upload CSV files')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadMOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=explainable.models.uploadmodel, validators=[explainable.models.valPKL], verbose_name='Only upload PKL models')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=explainable.models.uploadtrain, validators=[explainable.models.valCSV], verbose_name='Only train CSV files')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
