# Generated by Django 4.2.7 on 2023-12-19 18:14

from django.db import migrations, models
import explainable.models


class Migration(migrations.Migration):

    dependencies = [
        ('explainable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtrain',
            name='upload_file',
            field=models.FileField(upload_to=explainable.models.uploadtrain, validators=[explainable.models.valCSV], verbose_name='Only upload CSV files'),
        ),
    ]
